version: "3"
services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: project

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root123
